### PR TITLE
Deploymentscripts

### PR DESCRIPTION
**Pull request by n0tspam**

### CODE REVIEW

**Review by n0tspam — COMMENTED** [review]
test commit for current deployment script deployPolygon.js. I know we are switching to typecript at some point, but I just wanted to get it working with JS since I am more familiar with it

**Comment by Schlagonia** [comment]
The scripts look good. Looks like there is a couple conflicts with the master. Can you just update your branch with the recent changes from the master to resolve those and then resubmit the PR

**Comment by n0tspam** [comment]
merge fix. current state is the template for the deployment scripts.

**Comment by n0tspam** [comment]
merge fix. current state is the template for the deployment scripts.

**Review by Schlagonia — COMMENTED** [review]
Looks Good

**Pull request merged**
